### ISSUE TITLE
[BUG] Random Nullpointer exc

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-PocketMobs#1]
**Describe the bug**
Random NPE exception

**To Reproduce**
unknown

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5
 - Client version: 1.16.5
 - Plugin version: Pocketmobs 1.0.25

**Additional context**
```
[00:15:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PocketMobs v1.0.25
java.lang.NullPointerException: ItemStack can't be null/Air!
	at dev.lone.LoneLibs.nbt.nbtapi.NBTItem.<init>(NBTItem.java:28) ~[?:?]
	at dev.lone.PocketMobs.c.c.a(SourceFile:252) ~[?:?]
	at dev.lone.PocketMobs.e.a(SourceFile:46) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-997]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-997]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-997]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-997]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:528) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1664) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1212) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1205) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1181) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1025) ~[patched_1.16.5.jar:git-Purpur-997]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Purpur-997]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-PocketMobs/issues/4
